[mypy]
files = arnio
python_version = 3.9
follow_imports = silent
ignore_missing_imports = True
disable_error_code = attr-defined, union-attr, index, return-value, arg-type, assignment, misc, operator, type-arg, var-annotated, no-untyped-def, no-any-return, no-untyped-call, call-overload, valid-type, unused-ignore

[mypy-arnio.io]
strict = True
disallow_any_generics = False
enable_error_code = attr-defined, union-attr, index, return-value, arg-type, assignment, misc, operator, type-arg, var-annotated, no-untyped-def, no-any-return, no-untyped-call, call-overload, valid-type, unused-ignore
